### ISSUE TITLE
Your request type is not valid

### ISSUE THREAD

**Issue by Saturn87930** [IRLToolkit/simpleobsws#10]
yuan = simpleobsws.Request('TakeSourceScreenshot', {'sourceName':"main", 'saveToFilePath':"D:\\images\\" , 'fileFormat':'png', 'compressionQuality':"-1", 'width':"1920", 'height':"1080"})
    ret2 = await ws.call(yuan)
    if ret2.ok():
        print("Request succeeded! Response data: {}".format(ret2.responseData))

My code is like this. Is there any problem? Why are errors always displayed. obs-version 27.2.4，   obs-websocket version 5， simpleobsws version 1.3.1. thanks！

**Comment by SigreRabbit** [comment]
> TakeSourceScreenshot

This protocol seems to have changed from v4.x to v5.0.

v4.x
https://github.com/obsproject/obs-websocket/blob/4.x-current/docs/generated/protocol.md#takesourcescreenshot

v5.0
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#savesourcescreenshot
