### ISSUE TITLE
warning. asyncio.get_event_loop deprecation

### ISSUE THREAD

**Issue by popcorn9499** [IRLToolkit/simpleobsws#11]
Not sure as of this exact moment the best way to handle this going forward but `asyncio.get_event_loop` is deprecated starting in python 3.10.

your best bet may be to either not store self.loop in the object and use `asyncio.get_running_loop`
or in something like connect which seems to be the first thing one may call `asyncio.get_running_loop` 

or better yet replace loop.create_task with `asyncio.create_task` as functionally for what you are doing these are in fact the same

**Comment by popcorn9499** [comment]
I created a pull request [here](https://github.com/IRLToolkit/simpleobsws/pull/12)

**Comment by Braekpo1nt** [comment]
This is happening to me as well
