### ISSUE TITLE
Docker does not execute requirements.txt

### ISSUE THREAD

**Issue by airbornelamb** [IRLToolkit/simpleobsws#14]
Docker-compose is not executing correctly because the Dockerfile is not referencing the requirements.txt file.

I have fixed to make this work and will submit a PR. @tt2468 can you label the repo with `hacktoberfest` topic?

**Comment by tt2468** [comment]
This repository does not have any relevance to docker.

**Comment by airbornelamb** [comment]
Dangit wrong repo - sorry
