### ISSUE TITLE
var typo `authresult` vs `authResult`

### ISSUE THREAD

**Issue by rjhornsby** [IRLToolkit/simpleobsws#2]
In https://github.com/IRLToolkit/simpleobsws/blob/d17028aef62e41e49f695ee794650da34dab6cbb/simpleobsws.py#L48-L51

lines 48 and 49, the var is called `authResult`, but in line 51 it's referred to as `authresult` (lowercase `r`)

I've made this sort of mistake/typo more times than I can remember. If it helps, python's style guide suggests[1] (in large part to set a "standard" so it's easy to remember) that variables be named all lowercase, and use `_` separators. In this specific case, that might be `auth_result`

HTH

[1] https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

**Comment by tt2468** [comment]
This was mainly due to using all lowercase (no underscores) and switching to camelCase code styling later on. At least its not a critical issue.

**Comment by rjhornsby** [comment]
The difference in the case means that Python sees the two as different variables. If the code reaches line 51, it will throw an exception `NameError: name 'authresult' is not defined`

Example snippet -

```
authResult = {"success": True, "error": "maybe" }
print(f"auth errors: #{authresult['error']}")
```
```
Traceback (most recent call last):
  File "scratch.py", line 5, in <module>
    print(f"auth errors: #{authresult['error']}")
NameError: name 'authresult' is not defined
```

**Comment by tt2468** [comment]
Yes, I've written python for about 4 years now.
