### ISSUE TITLE
How can I change scene?

### ISSUE THREAD

**Issue by Barabba11** [IRLToolkit/simpleobsws#3]
Hi! Sorry to report a bug to ask help how to change scene, may you please share with me an example? Thank you a lot
I've just figured out (after more than one hour) that OBS doesn't support sendkeys ((((( it was very easy to suppose a simple keystroke can solve my problem..
Thank you!

**Comment by tt2468** [comment]
Here's the obs-websocket protocol which has all of the requests you might be looking for, including `TriggerHotkeyByName`: https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#triggerhotkeybyname

Here's an example of `SetCurrentScene`:
```python
data = {'scene-name': 'Scene 2'}
result = await ws.call('SetCurrentScene', data)
```

**Comment by Barabba11** [comment]
Thank you a lot! I've implement this into the python file an I'm able to change the scene :)

**Comment by Barabba11** [comment]
Mate, I would like to ask you, I'm sure your knowledge about OBS can help me find a solution..
my goal is to return to the main scene when the scene is changed, now thanks to you I now how to change scene but the way I considered valid, obs-scene-execute-command-script, has bad sides: it opens a dos prompt and it frozes the streams until the command is completed. 
Now I want to wait 1-2 minutes before put the scene back to default, how may I do it? Simply execute your Python script would be great.. (without open a lua dos prompt). There is another thing to consider, if the scene will be changed during that time too the script timeout should be reinitialized, or the prevuous script killed.
THank you a lot for any info )

**Comment by Barabba11** [comment]
For who may be interested, I hope I've solved with that script which actually starts a (obs-scene-execute-command-script) which actaully starts a python script, where I kill all cmd.exe process, then it executes a bat file where I kill all phyton processes, and then execute the python to switch scene. In this way, if I press quick different channels, the previous srit will be terminated anycase and the new one will take effect on newxt 2 min
