### ISSUE TITLE
Samples do not work: "module 'simpleobsws' has no attribute 'IdentificationParameters'"

### ISSUE THREAD

**Issue by kannes** [IRLToolkit/simpleobsws#4]
I installed the module via `pip install simpleobsws`.
When I try to run the samples from https://github.com/IRLToolkit/simpleobsws/tree/master/samples it fails right away with `AttributeError: module 'simpleobsws' has no attribute 'IdentificationParameters'`

`simpleobsws==0.0.7` with `conda` on Windows x86_64.

**Comment by tt2468** [comment]
For version 0.0.7 you should use the samples here: https://github.com/IRLToolkit/simpleobsws/blob/simpleobsws-4.x/samples/

The samples in the master branch are for the upcoming 1.0.0 release of simpleobsws which is for obs-websocket version 5.0.0 or greater.

**Comment by kannes** [comment]
Thanks for the premium level 24/7 response time :)
