### ISSUE TITLE
Consider changing the license to LGPL or MIT

### ISSUE THREAD

**Issue by bdrung** [IRLToolkit/simpleobsws#5]
I plan to develop a patch for [streamdeck-ui](https://github.com/timothycrosley/streamdeck-ui) to use Python library for obs-websocket to directly communicate with OBS. streamdeck-ui is licensed under MIT.

The other Python obs-websocket libraries are licensed under MIT. Your library uses GPL which will enforce all application using your library to be under GPL as well. Please consider changing the license to LGPL or even better MIT. Then changes to the library need to be published under LGPL, but applications using the library can use whatever they like.

**Comment by tt2468** [comment]
Done.

**Comment by bdrung** [comment]
Thank you.

**Comment by sebastian-sus** [comment]
Can the MIT license also be applied to the default branch `master`?

**Comment by bdrung** [comment]
The license change commit is in the `master` branch as well now.
