### ISSUE TITLE
`ws.wait_until_identified` times out causing `NotIdentifiedError`

### ISSUE THREAD

**Issue by ElPiloto** [IRLToolkit/simpleobsws#8]
Hello, I'm trying to run `sample_request.py` from the samples, but I can't seem to get a connection to my obs websocket.

When I run `sample_request.py` this is what I see in the obs logs:

```
00:55:04.121: ------------------------------------------------
00:55:04.404: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
00:55:04.407: [obs-websocket] server started successfully on port 4444
00:55:04.407: [obs-websocket] IO thread started.
00:55:11.581: [obs-websocket] new client connection from [::ffff:127.0.0.1]:57954
00:56:51.609: [obs-websocket] Websocket connection with client 'Unknown' closed (disconnected). Code is 1006, reason is: 'End of File'
```
I tried increasing the `timeout` parameter to `wait_until_identified` but that only caused a delay before repeating the same behavior.

Any pointers on how to debug this?

System info:
Ubuntu 20.04, using obs-websocket-4.9.1 and simpleobsws installed via `pip install` which gave me version 1.3.1

**Comment by ElPiloto** [comment]
And immediately after posting this I read the release notes here: https://github.com/IRLToolkit/simpleobsws/releases/tag/1.2.1 which say releases 1.1/2/3 are not compatible with obs-websockets-4.X  It looks like [obs-websocket-5.0.0 ](https://github.com/obsproject/obs-websocket/releases)is in pre-release alpha, is there a particular version I should grab?

**Comment by tt2468** [comment]
The protocol between 4.x and 5.x is completely different. Either upgrade to 5.0.0 and use 5.x requests, or use 4.9.1 with simpleobsws <1.0.0
