### ISSUE TITLE
Updating Text GDI - "your request type is not valid"

### ISSUE THREAD

**Issue by gitagogaming** [IRLToolkit/simpleobsws#9]
I am attempting to utilize this to make a batch update of text sources and am trying to make a proper change to a single TextGDI and when attempting to do so I am running into this errror. 

not sure what I am doing wwrong, I've tried multiple ways and other 'things' and i keep getting "your request type is not valid"
I've tried other requests which are not in the samples and they wont work either? 
like GetSourcesList for example

```    
eq = simpleobsws.Request('SetTextGDIPlusProperties', {'source': "Test Text GDI", 'text': "Test Text GDI"})
    ret = await ws.call(req)

```
    requests.append(simpleobsws.Request('GetVersion')) # Build a Request object, then append it to the batch
    requests.append(simpleobsws.Request('GetStats')) # Build another request object, and append it
    requests.append(simpleobsws.Request('SetTextGDIPlusProperties', {'source': "TEST TEXT GDI", 'text': "Miracle?"}))
    ret = await ws.call_batch(requests, halt_on_failure = False) # Perform the request batch
    print(ret)

```
    text = "Testtting"
    data = {"sourceName": "Test Text GDI", "text": text}

    result = await ws.call('SetTextGDIPlusProperties', data) # Make a request with the given data    
    print(result)

**Comment by gitagogaming** [comment]
Trying other things today like GetSceneitemProperties and it doesnt seem to be giving me the right response either, but get sceneitemID does... and sceneitemtransform  

I really feel as if I'm missing something obvious but I'm using the examples given along with the websocket documentation and seems like ive got everything right

**Comment by tt2468** [comment]
Make sure you are using 4.9.1 with simpleobsws<1.0.0 *or* 5.0.0* with simpleobsws>=1.0.0, as there was an api break at that version.
